pool:
  vmImage: "windows-2019"

variables:
  BuildConfiguration: "Release"

steps:
  - task: tmarkovski.projectversionasvariable.versionintovariable.projectversionasvariable@1
    displayName: "Get Project Version as variables from Etch.OrchardCore.Leaflet.csproj"
    inputs:
      path: ./Etch.OrchardCore.Leaflet/Etch.OrchardCore.Leaflet.csproj

  - task: MSBuild@1
    displayName: "Build tile generator"
    inputs:
      solution: "./Etch.OrchardCore.LeafletTileGenerator/Etch.OrchardCore.LeafletTileGenerator.csproj"
      configuration: $(BuildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: "Build tile generator"
    inputs:
      arguments: "-c $(BuildConfiguration)"
      command: "msbuild"
      projects: "./Etch.OrchardCore.LeafletTileGenerator/Etch.OrchardCore.LeafletTileGenerator.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Build module"
    inputs:
      arguments: "-c $(BuildConfiguration)"
      projects: "./Etch.OrchardCore.Leaflet/Etch.OrchardCore.Leaflet.csproj"

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: pack
      packagesToPack: "./Etch.OrchardCore.Leaflet/Etch.OrchardCore.Leaflet.csproj"
      versioningScheme: byPrereleaseNumber
      majorVersion: "$(Version.Major)"
      minorVersion: "$(Version.Minor)"
      patchVersion: "$(Version.Patch)"

  - task: PublishPipelineArtifact@0
    displayName: "Publish Pipeline Artifact"
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)"
